# English translations for nova_powervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 6.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-03-19 18:06-0400\n"
"PO-Revision-Date: 2018-03-19 18:07-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=n>1;"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: nova_powervm/virt/powervm/driver.py:216
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Esperado exatamente um host; localizados %d"

#: nova_powervm/virt/powervm/driver.py:821
#, python-format
msgid ""
"The snapshot operation is not supported in conjunction with a "
"CONF.powervm.disk_driver setting of %s."
msgstr ""
"A operação de captura instantânea não é suportada em conjunto com uma "
"configuração CONF.powervm.disk_driver de %s."

#: nova_powervm/virt/powervm/driver.py:1023
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Plugue vif falhou porque a instância %s não foi localizada."

#: nova_powervm/virt/powervm/driver.py:1028
msgid "Plug vif failed because of an unexpected error."
msgstr "Plugue vif falhou devido a erro inesperado."

#: nova_powervm/virt/powervm/driver.py:1118
msgid "Cannot reduce disk size."
msgstr "Impossível reduzir o tamanho do disco."

#: nova_powervm/virt/powervm/driver.py:1132
#: nova_powervm/virt/powervm/driver.py:1240
msgid "Cannot migrate local disks."
msgstr "Não é possível migrar discos locais."

#: nova_powervm/virt/powervm/driver.py:1757
#, python-format
msgid ""
"VNC based terminal for instance %(instance_name)s failed to open: "
"%(exc_msg)s"
msgstr ""
"O VNC baseado em terminal para a instância %(instance_name)s falhou ao abrir: "
"%(exc_msg)s"

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Não é possível localizar o grupo de volumes %(vol_grp)s no qual armazenar a mídia "
"virtual ótica. Impossível criar o repositório de mídia."

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"Tendo barramento SCSI digitalizado %(bus)x na partição de gerenciamento, disco com "
"UDID%(udid)s falhou em aparecer após as pesquisas %(polls)d em %(timeout)d "
"segundos."

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Esperava localizar exatamente um disco na partição de gerenciamento no "
"%(path_pattern)s; localizado%(count)d."

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"O dispositivo %(devpath)s ainda está presente na partição de gerenciamento após "
"tentar excluí-lo.  Pesquisado %(polls)d vezes em %(timeout)d "
"segundos."

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Falha em mapear o disco de inicialização da instância %(instance_name)s para a partição de "
"gerenciamento de qualquer Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Falha ao localizar o mapeamento recém-criado do elemento de armazenamento %(stg_name)s do"
" Virtual I/O Server %(vios_name)s para a partição de gerenciamento."

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Não é possível localizar o grupo de volumes '%(vg_name)s' para esta operação."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Não é possível localizar o Cluster '%(clust_name)s' para esta operação."

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "Não é possível localizar um cluster para esta operação."

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"Clusters com nomes correspondentes %(clust_count)d localizados inesperadamente "
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"Nenhum cluster_name especificado.  Recusando-se selecionar um dos %(clust_count)d"
" localizados."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Não é possível conectar o armazenamento (ID: %(volume_id)s) à máquina virtual "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to extend volume (id: %(volume_id)s) on virtual machine "
"%(instance_name)s."
msgstr ""
"Não é possível estender o volume (id:%(volume_id)s) na máquina virtual "
"%(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Não é possível remover o volume (ID: %(volume_id)s) da máquina virtual "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Não é possível executar as etapas de pré-migração em tempo real no volume (id:%(volume_id)s) "
"a partir da máquina virtual %(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "A API do PowerVM falhou em concluir instance=%(inst_name)s.%(reason)s"

#: nova_powervm/virt/powervm/exception.py:125
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a"
" VIOS to become active for %(wait_time)d seconds.  The compute agent is "
"not able to start if no Virtual I/O Servers are available.  Please check "
"the RMC connectivity between the PowerVM NovaLink and the Virtual I/O "
"Servers and then restart the Nova Compute Agent."
msgstr ""
"Nenhum Virtual I/O Server está disponível.  O driver tentou aguardar um"
" VIOS (Virtual I/O Server) se tornar ativo por %(wait_time)d segundos.  O agente de cálculo "
"não é capaz de iniciar se nenhum Virtual I/O Server está disponível.  Verifique "
"a conectividade do RMC entre o PowerVM NovaLink e o Virtual I/O "
"Server e, em seguida, reinicie o Nova Compute Agent."

#: nova_powervm/virt/powervm/exception.py:134
msgid "There are no active Virtual I/O Servers available."
msgstr "Não há nenhum Virtual I/O Server ativo disponível."

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "Não é possível reconstruir a máquina virtual no novo host.  O erro é %(error)s"

#: nova_powervm/virt/powervm/exception.py:143
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"A opção %(then_opt)s será necessária se %(if_opt)s for especificado como "
"'%(if_value)s'."

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Migração em tempo real da instância %(name)s' falhou devido a: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossível migrar %(name)s porque o volume %(volume)s não pode ser anexado "
"no host de destino %(host)s."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossível migrar %(name)s porque o host %(host)s somente permite %(allowed)s"
" migrações simultâneas e %(running)s migrações está em execução no momento."

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossível migrar instância '%(name)s' porque o tamanho da região de memória da "
"origem (%(source_mrs)d MB) não corresponde ao tamanho da região de memória do "
"destino (%(target_mrs)d MB)."

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossível migrar %(name)s porque seu modo de capacidade de processador %(mode)s"
" não está na lista de modos \"%(modes)s\" suportados pelo host de destino."

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"Migração em tempo real da instância '%(name)s' falhou porque o estado da migração "
"é: %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:455
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"A migração em tempo real da instância '%(name)s' falhou porque ela não está pronta. "
"Motivo: %(reason)s"

#: nova_powervm/virt/powervm/vif.py:85
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "o parâmetro vif_type deve estar presente para esta implementação de vif_driver"

#: nova_powervm/virt/powervm/vif.py:95
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s "
"on instance %(instance)s"
msgstr ""
"Não é possível localizar o driver da VIF do PowerVM apropriado para o tipo de VIF %(vif_type)s "
"na instância %(instance)s"

#: nova_powervm/virt/powervm/vif.py:540
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network "
"'%(physnet)s' for instance %(inst)s for SRIOV based VIF with MAC address "
"%(vif_mac)s."
msgstr ""
"Não é possível localizar portas Ethernet aceitáveis na rede física "
"'%(physnet)s' para a instância %(inst)s para o VIF baseado em SRIOV com endereço MAC "
"%(vif_mac)s."

#: nova_powervm/virt/powervm/vm.py:449
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Vários conjuntos de processo compartilhados com o nome %(pool)s."

#: nova_powervm/virt/powervm/vm.py:453
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossível localizar o conjunto de processamento compartilhado %(pool)s"

#: nova_powervm/virt/powervm/vm.py:475
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"O atributo flavor %(attr)s deve ser True ou False.  O valor atual "
"%(val)s não é permitido."

#: nova_powervm/virt/powervm/disk/driver.py:129
msgid "The configured disk driver does not support migration or resize."
msgstr "O driver do disco configurado não suporta migração ou redimensionamento."

#: nova_powervm/virt/powervm/disk/localdisk.py:300
msgid "Resizing file-backed instances is not currently supported."
msgstr "O redimensionamento das instâncias suportadas por arquivo não é suportado atualmente."

#: nova_powervm/virt/powervm/disk/ssp.py:119
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host "
"cluster: %(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"O host não é um membro do mesmo cluster do SSP. A máquina do host de origem "
"cluster: %(source_clust_name)s. O SSP do host de origem: %(source_ssp_name)s."

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"O NVRAM não pôde ser armazenado para a instância %(instance)s. Razão: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"O NVRAM não pôde ser buscado para a instância %(instance)s. Razão: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"O NVRAM não pôde ser excluído para a instância %(instance)s. Razão: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "A opção de configuração '%(option)s' deve ser configurada."

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "Não é possível armazenar a NVRAM (memória de acesso aleatório não volátil) após %d tentativas"

#: nova_powervm/virt/powervm/nvram/swift.py:272
msgid "Object does not exist in Swift."
msgstr "O objeto não existe no Swift."

#: nova_powervm/virt/powervm/volume/__init__.py:65
#, python-format
msgid "Invalid connection type of %s"
msgstr "Tipo de conexão inválida de %s"

#: nova_powervm/virt/powervm/volume/npiv.py:522
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"Não é possível localizar um Virtual I/O Server que hospede o mapa de porta NPIV para o "
"servidor rabbitmq."

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Falha em descobrir hdisk válido em qualquer Virtual I/O Server para o volume "
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O "
"Servers.  Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers,"
" but the disk was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"Falha ao descobrir o hdisk no número necessário de Virtual I/O "
"Server.  O volume %(volume_id)s requeria %(vios_req)d Virtual I/O Servers,"
" mas o disco somente foi localizado em %(vios_act)d Virtual I/O Servers."


# ENGL1SH_VERS10N 62006_10 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC141AAP001 1
