# English translations for nova_powervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 6.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-03-19 18:06-0400\n"
"PO-Revision-Date: 2018-03-19 18:07-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=n>1;"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: nova_powervm/virt/powervm/driver.py:216
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Précisément un hôte attendu ; trouvé %d"

#: nova_powervm/virt/powervm/driver.py:821
#, python-format
msgid ""
"The snapshot operation is not supported in conjunction with a "
"CONF.powervm.disk_driver setting of %s."
msgstr ""
"Opération d'instantané non prise en charge en association avec "
"un paramètre CONF.powervm.disk_driver de %s."

#: nova_powervm/virt/powervm/driver.py:1023
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Echec de connexion vif car l'instance %s est introuvable."

#: nova_powervm/virt/powervm/driver.py:1028
msgid "Plug vif failed because of an unexpected error."
msgstr "Echec de connexion vif en raison d'une erreur inattendue."

#: nova_powervm/virt/powervm/driver.py:1118
msgid "Cannot reduce disk size."
msgstr "Impossible de réduire la taille du disque."

#: nova_powervm/virt/powervm/driver.py:1132
#: nova_powervm/virt/powervm/driver.py:1240
msgid "Cannot migrate local disks."
msgstr "Impossible de migrer des disques locaux."

#: nova_powervm/virt/powervm/driver.py:1757
#, python-format
msgid ""
"VNC based terminal for instance %(instance_name)s failed to open: "
"%(exc_msg)s"
msgstr ""
"Echec d'ouverture du terminal basé VNC pour l'instance %(instance_name)s : "
"%(exc_msg)s"

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Impossible de localiser le groupe de volumes %(vol_grp)s dans lequel "
"est stocké le support optique virtuel. Impossible de créer "
"le référentiel de supports."

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"Après analyse du bus SCSI %(bus)x sur la partition de gestion, le disque "
"avec l'UDID %(udid)s n'est pas apparu après %(polls)d interrogations en "
"%(timeout)d secondes."

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Précisément un disque attendu sur la partition de gestion à l'adresse "
"Attendu %(path_pattern)s ; trouvé %(count)d."

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"L'unité %(devpath)s est encore présente sur la partition de gestion après "
"la tentative de suppression. %(polls)d interrogations en %(timeout)d "
"secondes."

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Echec du mappage du disque d'amorçage de l'instance %(instance_name)s "
"sur la partition de gestion depuis tout serveur Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Echec de détection du mappage nouvellement créé de l'élément de stockage"
" %(stg_name)s du serveur VIOS %(vios_name)s vers la partition de gestion."

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Impossible de localiser le groupe de volumes '%(vg_name)s' pour cette opération."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Impossible de localiser la grappe '%(clust_name)s' pour cette opération."

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "Impossible de localiser une grappe pour cette opération."

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"Détection inattendue de %(clust_count)d grappes avec un nom correspondant. "
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"Aucun cluster_name spécifié.  Refus de sélectionner une des %(clust_count)d"
" grappes détectées."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossible de connecter le stockage (ID : %(volume_id)s) à la machine "
"virtuelle %(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to extend volume (id: %(volume_id)s) on virtual machine "
"%(instance_name)s."
msgstr ""
"Impossible d'étendre le volume (ID : %(volume_id)s) de la machine "
"virtuelle %(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossible de déconnecter le volume (ID : %(volume_id)s) de la machine "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Impossible d'effectuer la procédure de pré-migration sur le volume "
"(ID : %(volume_id)s) depuis la machine virtuelle %(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "Echec de l'API PowerVM pour l'instance=%(inst_name)s.%(reason)s"

#: nova_powervm/virt/powervm/exception.py:125
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a"
" VIOS to become active for %(wait_time)d seconds.  The compute agent is "
"not able to start if no Virtual I/O Servers are available.  Please check "
"the RMC connectivity between the PowerVM NovaLink and the Virtual I/O "
"Servers and then restart the Nova Compute Agent."
msgstr ""
"Aucun serveur VIOS disponible.  Le pilote a tenté d'attendre qu'un VIOS"
" soit disponible pendant %(wait_time)d s. L'agent de calcul ne peut pas "
"démarrer si aucun serveur VIOS n'est disponible. Vérifiez la connectivité "
"RMC entre les serveurs PowerVM NovaLink et Virtual I/O Server, puis "
"redémarrez l'aget de calcul Nova. "

#: nova_powervm/virt/powervm/exception.py:134
msgid "There are no active Virtual I/O Servers available."
msgstr "Aucun serveur Virtual I/O Server actif disponible."

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "Impossible de régénérer la machine virtuelle sur le nouvel hôte.  Erreur : %(error)s"

#: nova_powervm/virt/powervm/exception.py:143
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"L'option %(then_opt)s est obligatoire si %(if_opt)s est spécifié pour "
"'%(if_value)s'."

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Echec de la migration active de l'instance '%(name)s' ; motif : %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossible de migrer %(name)s car le volume %(volume)s ne peut pas être "
"connecté à l'hôte de destination %(host)s."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossible de migrer %(name)s car l'hôte %(host)s autorise smt %(allowed)s"
" %(allowed)s migrations simultanées et %(running)s sont déjà en cours."

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossible de migrer l'instance '%(name)s' car la taille de région de "
"mémoire de la source (%(source_mrs)d Mo) ne correspond pas à celle de "
"la cible (%(target_mrs)d Mo)."

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossible de migrer %(name)s car son mode de compatibilité processeur"
" %(mode)s n'est pas dans la liste de modes \"%(modes)s\" pris en charge "
"par l'hôte cible."

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"Echec de la migration active de l'instance '%(name)s' car l'état de "
"la migration est %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:455
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"Echec de la migration active de l'instance '%(name)s' car non prête. "
"Motif : %(reason)s"

#: nova_powervm/virt/powervm/vif.py:85
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "Le paramètre vif_type doit être présent pour cette implémentation de vif_driver."

#: nova_powervm/virt/powervm/vif.py:95
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s "
"on instance %(instance)s"
msgstr ""
"Pilote VIF PowerVM approprié introuvable pour le type VIF %(vif_type)s "
"sur l'instance %(instance)s"

#: nova_powervm/virt/powervm/vif.py:540
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network "
"'%(physnet)s' for instance %(inst)s for SRIOV based VIF with MAC address "
"%(vif_mac)s."
msgstr ""
"Impossible de trouver des ports Ethernet acceptables sur le réseau "
"physique '%(physnet)s' pour l'instance %(inst)s pour SRIOV basé VIF "
"avec l'adresse MAC %(vif_mac)s."

#: nova_powervm/virt/powervm/vm.py:449
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Plusieurs pools de traitement partagé avec le nom %(pool)s."

#: nova_powervm/virt/powervm/vm.py:453
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossible de trouver le pool de traitement partagé %(pool)s"

#: nova_powervm/virt/powervm/vm.py:475
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"L'attribut de style %(attr)s doit être Vrai ou Faux. La valeur en cours "
"%(val)s n'est pas admise."

#: nova_powervm/virt/powervm/disk/driver.py:129
msgid "The configured disk driver does not support migration or resize."
msgstr "Le pilote de disque configuré ne prend pas en charge la migration ou le redimensionnement."

#: nova_powervm/virt/powervm/disk/localdisk.py:300
msgid "Resizing file-backed instances is not currently supported."
msgstr "Le redimensionnement des instances à base de fichiers n'est pas pris en charge actuellement."

#: nova_powervm/virt/powervm/disk/ssp.py:119
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host "
"cluster: %(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"L'hôte n'est pas membre de la même grappe SSP. Grappe d'hôtes "
"source : %(source_clust_name)s. SSP hôte source : %(source_ssp_name)s."

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossible stocker NVRAM pour l'instance %(instance)s. Motif : "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossible extraire NVRAM pour l'instance %(instance)s. Motif : "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossible supprimer NVRAM pour l'instance %(instance)s. Motif : "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "L'option de configuration '%(option)s' doit être définie."

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "Impossible de stocker la mémoire rémanente après %d tentatives"

#: nova_powervm/virt/powervm/nvram/swift.py:272
msgid "Object does not exist in Swift."
msgstr "L'objet n'existe pas dans Swift."

#: nova_powervm/virt/powervm/volume/__init__.py:65
#, python-format
msgid "Invalid connection type of %s"
msgstr "Type de connexion non valide : %s"

#: nova_powervm/virt/powervm/volume/npiv.py:522
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"Impossible de trouver un serveur VIOS hébergeant la mappe de port NPIV "
"pour le serveur."

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Echec de reconnaissance de hdisk valide sur un serveur Virtual I/O Server "
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O "
"Servers.  Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers,"
" but the disk was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"Echec de reconnaissance du hdisk sur le nombre requis de serveurs "
"Virtual I/O Server.  Volume %(volume_id)s requérant %(vios_req)d serveurs"
" VIOS mais disque détecté seulement sur %(vios_act)d serveurs VIOS."


# ENGL1SH_VERS10N 62006_10 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC141AAP001 1
