# English translations for nova_powervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 6.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-03-19 18:06-0400\n"
"PO-Revision-Date: 2018-03-19 18:07-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: nova_powervm/virt/powervm/driver.py:216
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "정확히 하나의 호스트를 예상했지만 %d개를 찾았습니다."

#: nova_powervm/virt/powervm/driver.py:821
#, python-format
msgid ""
"The snapshot operation is not supported in conjunction with a "
"CONF.powervm.disk_driver setting of %s."
msgstr ""
"스냅샷 조작은 CONF.powervm.disk_driver 설정이 "
"%s인 경우에는 지원되지 않습니다. "

#: nova_powervm/virt/powervm/driver.py:1023
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "%s 인스턴스를 찾을 수 없으므로 vif 플러그에 실패했습니다."

#: nova_powervm/virt/powervm/driver.py:1028
msgid "Plug vif failed because of an unexpected error."
msgstr "예기치 않은 오류 때문에 vif 플러그에 실패했습니다."

#: nova_powervm/virt/powervm/driver.py:1118
msgid "Cannot reduce disk size."
msgstr "디스크 크기를 줄일 수 없습니다."

#: nova_powervm/virt/powervm/driver.py:1132
#: nova_powervm/virt/powervm/driver.py:1240
msgid "Cannot migrate local disks."
msgstr "로컬 디스크를 마이그레이션할 수 없습니다."

#: nova_powervm/virt/powervm/driver.py:1757
#, python-format
msgid ""
"VNC based terminal for instance %(instance_name)s failed to open: "
"%(exc_msg)s"
msgstr ""
"인스턴스 %(instance_name)s에 대한 VNC 기반 터미널을 열지 못함: "
"%(exc_msg)s"

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"가상 광학 매체가 저장될 볼륨 그룹 %(vol_grp)s을(를) "
"찾을 수 없습니다. 매체 저장소를 작성할 수 없습니다."

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"관리 파티션에서 SCSI 버스 %(bus)x을(를) 스캔한 경우, "
"UDID %(udid)s의 디스크가 %(timeout)d초 동안 %(polls)d번 폴링한 이후 발견되지 "
"않습니다."

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"%(path_pattern)s에서 관리 파티션의 디스크를 정확히 하나를 "
"찾을 것으로 예상했지만, %(count)d개를 찾았습니다. "

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"삭제를 시도한 후에 장치 %(devpath)s이(가) 아직 관리 파티션에 "
"존재합니다. %(timeout)d초 동안 %(polls)d번 "
"폴링했습니다."

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"인스턴스 %(instance_name)s의 부트 디스크를 "
"Virtual I/O Server의 관리 파티션에 맵핑할 수 없습니다. "

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Virtual I/O Server %(vios_name)s에서 관리 파티션으로 "
" 스토리지 요소 %(stg_name)s의 새로 작성된 맵핑을 찾을 수 없습니다. "

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "이 조작의 볼륨 그룹 '%(vg_name)s'을(를) 찾을 수 없습니다. "

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "이 조작의 클러스터 '%(clust_name)s'을(를) 찾을 수 없습니다. "

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "이 조작의 클러스터를 찾을 수 없습니다."

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"다음 이름과 일치하는 %(clust_count)d개의 클러스터를 예상치 않게 찾았습니다."
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"cluster_name이 지정되지 않습니다. 발견된 %(clust_count)d개의 "
" 클러스터 중 하나를 선택할 것을 거부 중입니다. "

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"스토리지(id: %(volume_id)s)를 가상 머신에 연결할 수 없습니다. "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to extend volume (id: %(volume_id)s) on virtual machine "
"%(instance_name)s."
msgstr ""
"가상 머신에서 볼륨(id: %(volume_id)s)을 확장할 수 없습니다. "
"%(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"가상 머신에서 볼륨(id: %(volume_id)s)의 연결을 끊을 수 없습니다. "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"볼륨(id: %(volume_id)s)의 이전 실시간 마이그레이션 단계를 "
"%(instance_name)s에서 수행할 수 없습니다. "

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "PowerVM API: instance=%(inst_name)s에 대해 완료에 실패했습니다. 이유: %(reason)s   "

#: nova_powervm/virt/powervm/exception.py:125
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a"
" VIOS to become active for %(wait_time)d seconds.  The compute agent is "
"not able to start if no Virtual I/O Servers are available.  Please check "
"the RMC connectivity between the PowerVM NovaLink and the Virtual I/O "
"Servers and then restart the Nova Compute Agent."
msgstr ""
"Virtual I/O Server를 사용할 수 없습니다. 드라이버가 VIOS의 활성화 시점까지 "
" %(wait_time)d초 동안 대기하려고 시도했습니다. Virtual I/O Server를 "
"사용할 수 없으면 계산 에이전트를 시작할 수 없습니다. PowerVM NovaLink 및 "
"Virtual I/O Server 간의 RMC 연결을 확인한 후"
"Nova 계산 에이전트를 다시 시작하십시오."

#: nova_powervm/virt/powervm/exception.py:134
msgid "There are no active Virtual I/O Servers available."
msgstr "활성 Virtual I/O Server가 사용 가능하지 않습니다. "

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "새 호스트에서 가상 머신을 다시 빌드할 수 없습니다. 오류: %(error)s"

#: nova_powervm/virt/powervm/exception.py:143
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"%(if_opt)s이(가) 지정된 경우 %(then_opt)s 옵션이 필요합니다."
"'%(if_value)s'."

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "인스턴스 '%(name)s'의 실시간 마이그레이션에 실패했습니다. 이유: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"볼륨 %(volume)s을(를) 대상 호스트 %(host)s에 연결할 수 없으므로 %(name)s을(를) "
"마이그레이션할 수 없습니다."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"호스트 %(host)s이(가) %(allowed)s 동시 마이그레이션만 허용하고 "
" %(running)s 마이그레이션이 현재 실행 중이므로 %(name)s을(를) 마이그레이션할 수 없습니다."

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"소스의 메모리 영역 크기(%(source_mrs)d MB)가 대상의 "
"메모리 영역 크기(%(target_mrs)d MB)와 일치하지 않으므로 "
"'%(name)s' 인스턴스를 마이그레이션할 수 없습니다."

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"해당 프로세서 호환성 모드 %(mode)s이(가) 대상 호스트에서 지원하는 모드 \"%(modes)s\"의 목록에 없으므로 "
" %(name)s을(를) 마이그레이션할 수 없습니다."

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"마이그레이션 상태가 %(state)s이므로 인스턴스 '%(name)s'의 실시간 마이그레이션에 "
"실패했습니다."

#: nova_powervm/virt/powervm/live_migration.py:455
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"인스턴스 '%(name)s'의 실시간 마이그레이션이 준비되지 않았으므로 실패했습니다. "
"이유: %(reason)s"

#: nova_powervm/virt/powervm/vif.py:85
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "이 vif_driver 구현을 위해 vif_type 매개변수가 존재해야 함"

#: nova_powervm/virt/powervm/vif.py:95
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s "
"on instance %(instance)s"
msgstr ""
"VIF 유형 %(vif_type)s에 해당하는 PowerVM VIF 드라이버를 "
"%(instance)s 인스턴스에서 찾을 수 없음"

#: nova_powervm/virt/powervm/vif.py:540
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network "
"'%(physnet)s' for instance %(inst)s for SRIOV based VIF with MAC address "
"%(vif_mac)s."
msgstr ""
"MAC 주소가 사용된 SRIOV 기반 VIF의 인스턴스 %(inst)s에 대해 "
"물리적 네트워크 '%(physnet)s'에서 허용되는 이더넷 포트를 찾을 수 없음"
"%(vif_mac)s."

#: nova_powervm/virt/powervm/vm.py:449
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "이름이 %(pool)s인 다중 공유 처리 풀"

#: nova_powervm/virt/powervm/vm.py:453
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "공유 처리 풀 %(pool)s을(를) 찾을 수 없음"

#: nova_powervm/virt/powervm/vm.py:475
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"플레이버 속성 %(attr)s은(는) true 또는 false여야 합니다. 현재 값 "
"%(val)s은(는) 허용되지 않습니다."

#: nova_powervm/virt/powervm/disk/driver.py:129
msgid "The configured disk driver does not support migration or resize."
msgstr "구성된 디스크 드라이버에서 마이그레이션 또는 크기 조정을 지원하지 않습니다."

#: nova_powervm/virt/powervm/disk/localdisk.py:300
msgid "Resizing file-backed instances is not currently supported."
msgstr "파일 지원 인스턴스 크기 조정이 현재 지원되지 않습니다."

#: nova_powervm/virt/powervm/disk/ssp.py:119
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host "
"cluster: %(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"호스트가 동일한 SSP 클러스터의 멤버가 아닙니다. 소스 호스트 "
"클러스터: %(source_clust_name)s. 소스 호스트 SSP: %(source_ssp_name)s."

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"인스턴스 %(instance)s에 대해 NVRAM을 저장할 수 없습니다. 이유: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"인스턴스 %(instance)s에 대해 NVRAM을 페치할 수 없습니다. 이유: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"인스턴스 %(instance)s에 대해 NVRAM을 삭제할 수 없습니다. 이유: "
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "구성 옵션 '%(option)s'을(를) 설정해야 합니다."

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "%d번의 시도 후에는 NVRAM을 저장할 수 없음"

#: nova_powervm/virt/powervm/nvram/swift.py:272
msgid "Object does not exist in Swift."
msgstr "Swift에 오브젝트가 없습니다."

#: nova_powervm/virt/powervm/volume/__init__.py:65
#, python-format
msgid "Invalid connection type of %s"
msgstr "%s의 올바르지 않은 연결 유형"

#: nova_powervm/virt/powervm/volume/npiv.py:522
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"서버에 대한 NPIV 포트 맵을 호스트하는 Virtual I/O Server를 찾을 수 "
"없습니다."

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"볼륨 %(volume_id)s에 대한 Virtual I/O Server에서 올바른 hdisk를 검색하는 데 "
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O "
"Servers.  Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers,"
" but the disk was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"필수 개수의 Virtual I/O Server에서 hdisk를 검색하지 못했습니다. "
"없었습니다. 볼륨 %(volume_id)s에서 %(vios_req)d Virtual I/O Server가 필요하지만, "
" 디스크는 %(vios_act)d개의 Virtual I/O Server에서만 검색되었습니다."


# ENGL1SH_VERS10N 62006_10 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC141AAP001 1
