# Translations template for nova_powervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 6.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-03-19 18:06-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: nova_powervm/virt/powervm/driver.py:216
#, python-format
msgid "Expected exactly one host; found %d"
msgstr ""

#: nova_powervm/virt/powervm/driver.py:821
#, python-format
msgid ""
"The snapshot operation is not supported in conjunction with a "
"CONF.powervm.disk_driver setting of %s."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1023
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1028
msgid "Plug vif failed because of an unexpected error."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1118
msgid "Cannot reduce disk size."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1132
#: nova_powervm/virt/powervm/driver.py:1240
msgid "Cannot migrate local disks."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1757
#, python-format
msgid ""
"VNC based terminal for instance %(instance_name)s failed to open: "
"%(exc_msg)s"
msgstr ""

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to extend volume (id: %(volume_id)s) on virtual machine "
"%(instance_name)s."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/exception.py:125
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a"
" VIOS to become active for %(wait_time)d seconds.  The compute agent is "
"not able to start if no Virtual I/O Servers are available.  Please check "
"the RMC connectivity between the PowerVM NovaLink and the Virtual I/O "
"Servers and then restart the Nova Compute Agent."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:134
msgid "There are no active Virtual I/O Servers available."
msgstr ""

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr ""

#: nova_powervm/virt/powervm/exception.py:143
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""

#: nova_powervm/virt/powervm/live_migration.py:455
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/vif.py:85
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr ""

#: nova_powervm/virt/powervm/vif.py:95
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s "
"on instance %(instance)s"
msgstr ""

#: nova_powervm/virt/powervm/vif.py:540
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network "
"'%(physnet)s' for instance %(inst)s for SRIOV based VIF with MAC address "
"%(vif_mac)s."
msgstr ""

#: nova_powervm/virt/powervm/vm.py:449
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr ""

#: nova_powervm/virt/powervm/vm.py:453
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr ""

#: nova_powervm/virt/powervm/vm.py:475
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""

#: nova_powervm/virt/powervm/disk/driver.py:129
msgid "The configured disk driver does not support migration or resize."
msgstr ""

#: nova_powervm/virt/powervm/disk/localdisk.py:300
msgid "Resizing file-backed instances is not currently supported."
msgstr ""

#: nova_powervm/virt/powervm/disk/ssp.py:119
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host "
"cluster: %(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr ""

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr ""

#: nova_powervm/virt/powervm/nvram/swift.py:272
msgid "Object does not exist in Swift."
msgstr ""

#: nova_powervm/virt/powervm/volume/__init__.py:65
#, python-format
msgid "Invalid connection type of %s"
msgstr ""

#: nova_powervm/virt/powervm/volume/npiv.py:522
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O "
"Servers.  Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers,"
" but the disk was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""

